### ISSUE TITLE
Can't find devices (doors).

### ISSUE THREAD

**Issue by bigmacd** [fuzzysb/Garadget#3]
Everything goes perfectly running the app.  It connects to Garadget with my credentials (Garadget is now connnected to SmartThings!), it also finds my device (called "Left_Door").  I then click done (I also tried clicking Install).  I will eventually get the following log messages:

fdf90371-3510-46c9-b034-28d6fe40b77b 3:30:04 PM: error java.lang.NullPointerException
fdf90371-3510-46c9-b034-28d6fe40b77b 3:30:04 PM: debug getChildDevices(false), children=22
fdf90371-3510-46c9-b034-28d6fe40b77b 3:30:04 PM: debug Initialized with settings: [devices:1d003d000451353432383931|Left_Door, garadgetUsername:martin@**********.com, garadgetPassword:**********]

Then in My Devices, I have:

![garadget](https://user-images.githubusercontent.com/4291065/34342800-8e2783f6-e989-11e7-93ba-5a7054519c21.png)

As you can see in the logs, it added 22 of these.

I can click Uninstall and all 22 devices are removed.

Any ideas?

**Comment by tjustil** [comment]
Having exact same problem, though mine creates 9 "nulls", not 22. And none of the devices successfully activates the door.

**Comment by fuzzysb** [comment]
Hi, i am trying to find possible a possible root cause for your issue. the only thing that potentially makes sense at the moment is if you already had other Particle.io devices registered to an account and you have used the same account details for Garadget. can you confirm if this is the case?

**Comment by tjustil** [comment]
Thanks Stuart. I actually resolved it this morning. Looking back at previous issues I caught a step that wasn’t in your original instructions: going into the marketplace in the app and setting up the door in my things. The nulls apparently were virtual doors set up when I ran the smart app simulator after publishing the smart app code.

Thanks,

Travis

--
Travis Justilian

**Comment by bigmacd** [comment]
@fuzzysb I do have particle.io devices registered to the same email account.  Anything I should do to get them out of the way?

@tjustil Can you elaborate?  I am not sure when that step needs to be executed. 

Thanks!

**Comment by tjustil** [comment]
This happens after you publish the Garadget (connect) app and it shows up in your apps for your location. You then go into the Smartthings iPhone app, go to marketplace, go to Smartapps, and then scroll all the way down and click my apps. You should fine garadget connect there. Authenticate and select your device(s), complete the steps and you should be good to go. I believe that when Stuart was referring to “authenticate” in his instructions, this is what he was referring to. Sounds like you did what I did, which was attempt to authenticate through the app simulator online, which is why you have all the null apps. By the way, once your real door(s) is set up and shows up in your list of devices, you can delete all the nulls in the devices tab on the web site (I don’t think you can do this in the iPhone app).

Thanks,

Travis

--
Travis Justilian

**Comment by bigmacd** [comment]
@tjustil Thanks!  Marketplace is a weird place to put "My SmartApps".  So glad you pointed it out!  So much makes sense now.  I have no idea how I got my TP-Link bulb installed, but I found the smartapp!  

@fuzzysb Thanks for the code.  It works great.  Just ordered my second unit now that I know it works.  Hat tip coming your way.

**Comment by fuzzysb** [comment]
@bigmacd much appreciated thanks. @tjustil thanks for your assistance and apologies in not actioning sooner. Marking the  closed
